In [6]:
L = [1, 3, 4.9, 'name', 3]
T = (1, 3, 4.9, 'name', 3)
S = {1, 3, 4.9, 'name', 3}

In [7]:
S = {1,2,3}

In [9]:
S2= S.copy()

In [10]:
S

{1, 2, 3}

In [11]:
S2

{1, 2, 3}

In [12]:
S2.append(4)

AttributeError: 'set' object has no attribute 'append'

In [13]:
S2[3] = 4

TypeError: 'set' object does not support item assignment

In [14]:
S

{1, 2, 3}

In [15]:
S2

{1, 2, 3}

In [17]:
S2.remove(2)

In [18]:
S2

{1, 3}

In [19]:
S

{1, 2, 3}

In [20]:
S3 = S + S2

TypeError: unsupported operand type(s) for +: 'set' and 'set'

In [25]:
D = {'A':'a', 'B':3}

In [31]:
D['A'][0]

'a'

In [33]:
for x in D:
    print(x, D[x])

A a
B 3


In [34]:
L3 = [x**2 for x in range(10)]

In [35]:
L3

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [41]:
def getDataFromUser():
    D = {}
    while True:
        studentId = input('Enter student ID: ')
        marksList = input('Enter the marks by comma separted values: ')
        moreStudents = input('Enter "no" to quit insertion: ')
        if studentId in D:
            print(studentId, 'is already inserted')
        else:
            D[studentId] = marksList.split(',')
        if moreStudents.lower() == 'no':
            return D

In [42]:
studentData = getDataFromUser()

Enter student ID: 1
Enter the marks by comma separted values: 24, 35, 32
Enter "no" to quit insertion: yes
Enter student ID: 2
Enter the marks by comma separted values: 33
Enter "no" to quit insertion: 1
Enter student ID: 1
Enter the marks by comma separted values: 23
Enter "no" to quit insertion: 2
1 is already inserted
Enter student ID: 3
Enter the marks by comma separted values: 23,33,43,42,45
Enter "no" to quit insertion: yt
Enter student ID: 5
Enter the marks by comma separted values: 45,45,45
Enter "no" to quit insertion: no


In [59]:
studentData

{'1': ['24', ' 35', ' 32'],
 '2': ['33'],
 '3': ['23', '33', '43', '42', '45'],
 '5': ['45', '45', '45']}

In [69]:
def getAvgMarks(D):
    avgMarks = {}
    for x in D:
        L = D[x]
        s = 0
        for marks in L:
            s += int(marks)
        avgMarks[x] = s/len(L)
    return avgMarks

In [70]:
avgM = getAvgMarks(studentData)

In [71]:
for x in avgM:
    print('Student: ',x,'got avg marks as: ', avgM[x])

Student:  1 got avg marks as:  30.333333333333332
Student:  2 got avg marks as:  33.0
Student:  3 got avg marks as:  37.2
Student:  5 got avg marks as:  45.0


In [72]:
import numpy as np

In [73]:
a = np.array([1,2,3,4,5])

In [74]:
print(a)

[1 2 3 4 5]


In [75]:
type(a)

numpy.ndarray

In [76]:
a.dtype

dtype('int32')

In [79]:
a = np.array([[1,2,3], [4,5,6]])

In [80]:
print(a)

[[1 2 3]
 [4 5 6]]


In [81]:
print(a.ndim)

2


In [86]:
print(a.shape[0])

2
